identifier: cricketarchive-ingester
title: CricketArchive Ingester
team: [main]
icon: DefaultBlueprint
blueprint: domain
properties:
  type: backend
  framework: Spring Boot
  importance: Low
relations:
  customer: ab_test_4
