identifier: cricketarchive-ingester
title: CricketArchive Ingester
team: [andromeda]
icon: DefaultBlueprint
blueprint: domain
properties:
  type: backend
  framework: Spring Boot
  importance: Low
relations:
  customers: ab_test_4
