name: Port Ocean Kafka Integration

# Kafka Exporter Workflow
# This workflow is responsible for running the Kafka exporter.
# cluster_conf_mapping: Mapping of Kafka cluster names to Kafka client config.
# Example: {"my cluster": {"bootstrap.servers": "localhost:9092"}}

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *' # Runs every hour

jobs:
  run-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # Set a time limit for the job

    steps:
      - name: Run Kafka Integration
        uses: port-labs/ocean-sail@v1
        with:
          type: kafka
          port_client_id: ${{ secrets.PORT_CLIENT_ID }}
          port_client_secret: ${{ secrets.PORT_CLIENT_SECRET }}
          port_base_url: "https://api.port.io"
          config: |
            cluster_conf_mapping: ${{ secrets.OCEAN__INTEGRATION__CONFIG__CLUSTER_CONF_MAPPING }}
