name: Dump Inputs Workflow

on:
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: "ID of the workflow run"
        required: true
        default: ""
      workflow_node_id:
        description: "ID of the workflow node"
        required: true
        default: ""
      workflow_node_id_two:
        description: "ID of the workflow node"
        required: true
        default: ""
jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print workflow_run_id and workflow_node_id
        run: |
          echo "workflow_run_id: ${{ github.event.inputs.workflow_run_id }}"
          echo "workflow_node_id: ${{ github.event.inputs.workflow_node_id }}"
           echo "workflow_node_id_two: ${{ github.event.inputs.workflow_node_id_two }}"
      - name: Dump full event payload
        run: echo '${{ toJson(github.event) }}'
